
export const GET_DISHES = 'GET_DISHES';
export const GET_DISHES_FAILED = 'GET_DISHES_FAILED';
export const DISHES_LOADING = 'DISHES_LOADING';

export const ADD_COMMENT = 'ADD_COMMENT';
export const ADD_COMMENT_FAILED = 'ADD_COMMENT_FAILED';
export const COMMENT_LOADING = 'COMMENT_LOADING';

export const ADD_PROMO = 'ADD_PROMO';
export const ADD_PROMO_FAILED = 'ADD_PROMO_FAILED';
export const PROMOS_LOADING = 'PROMOS_LOADING';

export const ADD_LEADERS = 'ADD_LEADERS';
export const ADD_LEADERS_FAILED = 'ADD_LEADERS_FAILED';
export const LEADERS_LOADING = 'LEADERS_LOADING';

export const ADD_FAVORITES = 'ADD_FAVORITES';